services:
  khabar:
    image: ghcr.io/ashlaiden/portal-khabar
    container_name: portal-khabar
    ports:
      - "8000:8000"
    volumes:
      - ~/db:/app/db
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=1234
      - DJANGO_SETTINGS_MODULE=apps.config.settings
      - ENABLE_SCHEDULER=true
    restart: unless-stopped