# Generated by Django 5.2 on 2026-06-17 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='نامک')),
                ('keywords', models.TextField(blank=True, help_text='کلمات کلیدی فارسی را با کاما جدا کنید. مثال: فوتبال، والیبال', verbose_name='کلمات کلیدی برای دسته\u200cبندی خودکار')),
                ('color', models.CharField(default='bg-indigo-500/20 text-indigo-300', max_length=40, verbose_name='رنگ نشان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام خبرگزاری')),
                ('url', models.URLField(unique=True, verbose_name='آدرس RSS')),
                ('website', models.URLField(blank=True, help_text='اختیاری؛ برای نمایش در منبع خبر', verbose_name='وب\u200cسایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('fetch_interval_minutes', models.PositiveIntegerField(default=30, help_text='هر چند دقیقه یک\u200cبار این فید بررسی شود.', verbose_name='بازه دریافت (دقیقه)')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین دریافت')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='آخرین خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('default_category', models.ForeignKey(blank=True, help_text='اگر دسته\u200cبندی هوشمند نتواند دسته\u200cای پیدا کند، از این استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='news.category', verbose_name='دسته پیش\u200cفرض')),
            ],
            options={
                'verbose_name': 'منبع RSS',
                'verbose_name_plural': 'منابع RSS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='نامک')),
                ('summary', models.TextField(blank=True, verbose_name='خلاصه')),
                ('content', models.TextField(blank=True, verbose_name='متن خبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/', verbose_name='تصویر آپلودی')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='آدرس تصویر (RSS)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('is_featured', models.BooleanField(default=False, verbose_name='خبر ویژه (صفحه خانه)')),
                ('is_rss', models.BooleanField(default=False, verbose_name='خبر RSS')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='نام خبرگزاری')),
                ('source_url', models.URLField(blank=True, verbose_name='لینک منبع')),
                ('dedup_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='هش یکتایی (ضد تکرار)')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='لایک')),
                ('dislikes_count', models.PositiveIntegerField(default=0, verbose_name='دیسلایک')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='دسته\u200cبندی')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.rssfeed', verbose_name='منبع RSS')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'), models.Index(fields=['is_published', 'is_featured'], name='news_articl_is_publ_4eddd8_idx'), models.Index(fields=['dedup_hash'], name='news_articl_dedup_h_7c6103_idx')],
            },
        ),
    ]
