# Generated by Django 5.2 on 2026-06-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(default='-', max_length=150, verbose_name='نام خبرگزاری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='دسته خبری'),
        ),
    ]
