# Generated by Django 5.2 on 2026-06-30 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rssfeed_title_alter_rssfeed_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام خبرگزاری')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='نامک')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('logo_url', models.URLField(blank=True, help_text='آدرس لوگوی خبرگزاری', verbose_name='آدرس لوگو')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'خبرگزاری',
                'verbose_name_plural': 'خبرگزاری\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='rssfeed',
            options={'ordering': ['id'], 'verbose_name': 'منبع RSS', 'verbose_name_plural': 'منابع RSS'},
        ),
        migrations.RemoveField(
            model_name='rssfeed',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rssfeed',
            name='title',
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='خبرگزاری مربوط به این فید RSS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='news.newsagency', verbose_name='خبرگزاری'),
        ),
    ]
