# Generated by Django 5.2 on 2026-06-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsagency_alter_rssfeed_options_remove_rssfeed_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='fetch_interval_minutes',
            field=models.PositiveIntegerField(default=5, help_text='هر چند دقیقه یک\u200cبار این فید بررسی شود.', verbose_name='بازه دریافت (دقیقه)'),
        ),
    ]
