# Generated by Django 5.2 on 2026-06-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_rssfeed_fetch_interval_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=350, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='newsagency',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True, verbose_name='نامک'),
        ),
    ]
