# Generated by Django 5.2 on 2026-06-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='آدرس تصویر (RSS)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=600, verbose_name='لینک منبع'),
        ),
        migrations.AlterField(
            model_name='newsagency',
            name='logo_url',
            field=models.URLField(blank=True, help_text='آدرس لوگوی خبرگزاری', max_length=500, verbose_name='آدرس لوگو'),
        ),
    ]
